// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PruegaProgreso1UlloaR.Migrations
{
    [DbContext(typeof(DBSqlServerUlloaRoberto))]
    [Migration("20250429192240_Migracion Inicial")]
    partial class MigracionInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PruegaProgreso1UlloaR.Models.Cliente", b =>
                {
                    b.Property<string>("Identificacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<bool>("EstadoActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaEntrada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaSalida")
                        .HasColumnType("datetime2");

                    b.Property<string>("RobertoUlloa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Identificacion");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("PruegaProgreso1UlloaR.Models.Recompensa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClienteIdentificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PuntosAcumulados")
                        .HasColumnType("int");

                    b.Property<string>("TipoRecompensa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteIdentificacion");

                    b.ToTable("Recompensa");
                });

            modelBuilder.Entity("PruegaProgreso1UlloaR.Models.Reserva", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReserva"));

                    b.Property<string>("ClienteIdentificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Pagar")
                        .HasColumnType("float");

                    b.HasKey("IdReserva");

                    b.HasIndex("ClienteIdentificacion");

                    b.ToTable("Reserva");
                });

            modelBuilder.Entity("PruegaProgreso1UlloaR.Models.Recompensa", b =>
                {
                    b.HasOne("PruegaProgreso1UlloaR.Models.Cliente", "Cliente")
                        .WithMany("Recompensa")
                        .HasForeignKey("ClienteIdentificacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("PruegaProgreso1UlloaR.Models.Reserva", b =>
                {
                    b.HasOne("PruegaProgreso1UlloaR.Models.Cliente", "Cliente")
                        .WithMany("Reserva")
                        .HasForeignKey("ClienteIdentificacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("PruegaProgreso1UlloaR.Models.Cliente", b =>
                {
                    b.Navigation("Recompensa");

                    b.Navigation("Reserva");
                });
#pragma warning restore 612, 618
        }
    }
}
